#!/usr/bin/env node

require('rubico/global')
const rubico = require('../rubico')
const Transducer = require('../rubico/Transducer')
const x = require('../rubico/x')
const IndexHtml = require('./internal/IndexHtml')
const FileSystem = require('./internal/FileSystem')

// FunctionNames() -> names Array<string>
const FunctionNames = function (lib) {
  const result = []
  for (const name in lib) {
    result.push(name)
    const fn = lib[name]
    for (const subName in fn) {
      result.push(`${name}.${subName}`)
    }
  }
  return result
}

/**
 * @name main
 *
 * @synopsis
 * ```coffeescript [specscript]
 * main(options {
 * }) -> Promise<>
 * ```
 */
const main = async function (options) {
  const publicFs = new FileSystem({ cwd: `${__dirname}/public` })

  await publicFs.rmrf('/index.html')
  await publicFs.rmrf('/tour')
  await publicFs.rmrf('/docs')
  await publicFs.rmrf('/blog')

  console.log('Creating index.html')
  await publicFs.writeFile('index.html', IndexHtml({
    path: '/',
    title: 'Rubico - [A]synchronous Functional Programming',
    description: 'A library for creating async-enabled function compositions.',
  }))

  console.log('Creating tour/index.html')
  await publicFs.writeFile('tour/index.html', IndexHtml({
    path: '/tour/',
    title: 'A tour of Rubico',
    description: 'An overview of the Rubico library',
  }))

  console.log('Creating docs/index.html')
  await publicFs.writeFile('docs/index.html', IndexHtml({
    path: '/docs/',
    title: 'Rubico documentation',
    description: 'A reference for the Rubico library',
  }))

  console.log('Creating blog/index.html')
  await publicFs.writeFile('blog/index.html', IndexHtml({
    path: '/blog/',
    title: 'Rubico blog',
    description: 'A blog about the Rubico library, JavaScript, and [A]synchronous Functional Programming',
  }))

  const coreFunctionNames = FunctionNames(rubico)
  const deprecatedFunctionNames = [
    'pipe.sync',
    'tap.sync',
    'fork',
    'fork.series',
    'map.withIndex',
    'map.own',
    'filter.withIndex',
    'not.sync',
  ]
  const transducerFunctionNames = FunctionNames(Transducer)

  for (const functionName of [
    coreFunctionNames,
    deprecatedFunctionNames,
  ].flat(1)) {
    console.log(`Creating docs/${functionName}`)
    await publicFs.writeFile(`docs/${functionName}`, IndexHtml({
      path: `/docs/${functionName}`,
      title: `${functionName} - Rubico documentation`,
      description: `Reference for ${functionName}`,
    }))
  }

  for (const functionName of transducerFunctionNames) {
    console.log(`Creating docs/${functionName}`)
    await publicFs.writeFile(`docs/Transducer.${functionName}`, IndexHtml({
      path: `/docs/Transducer.${functionName}`,
      title: `Transducer.${functionName} - Rubico documentation`,
      description: `Reference for Transducer.${functionName}`,
    }))
  }

  const xFunctionNames = FunctionNames(x)

  for (const functionName of xFunctionNames) {
    console.log(`Creating docs/x/${functionName}`)
    await publicFs.writeFile(`docs/x/${functionName}`, IndexHtml({
      path: `/docs/x/${functionName}`,
      title: `x/${functionName} - Rubico documentation`,
      description: `Reference for x/${functionName}`,
    }))
  }

  const articlesFs = new FileSystem({ cwd: `${__dirname}/articles` })

  for (const filename of await articlesFs.find('.')) {
    const content = await articlesFs.cat(filename)
    const parts = content.split('---')

    // skip articles without metadata
    if (parts.length == 1) {
      continue
    }

    const metadata = pipe(parts, [
      get(1),
      x.callProp('trim'),
      x.callProp('split', '\n'),
      map(x.callProp('split', ': ')),
      Object.fromEntries,
    ])

    const { path, title, description, image } = metadata

    console.log('Creating', path)
    await publicFs.writeFile(path, IndexHtml({ path, title, description, image }))
  }
}

if (require.main == module) {
  main()
}

module.exports = main
