#!/usr/bin/env node

const AwsCredentials = require('presidium/AwsCredentials')
const S3Bucket = require('presidium/S3Bucket')
const S3Website = require('./internal/S3Website')

;(async function () {
  const awsCreds = await AwsCredentials('solum')
  awsCreds.region = 'us-east-1'

  const websiteBucket = new S3Bucket({
    name: 'rubico.land',
    ...awsCreds,
  })
  await websiteBucket.ready

  await new S3Website(websiteBucket).deploy({
    rootPath: `${__dirname}/public`,
    concurrency: 10,
  })

})()
