#!/usr/bin/env node

const AwsCredentials = require('presidium/AwsCredentials')
const SecretsManager = require('presidium/SecretsManager')
const package = require('./package.json')
const serve = require('./serve')

setImmediate(async () => {
  const env = 'production'
  const awsCreds = await AwsCredentials('solum')
  awsCreds.region = 'us-east-1'

  const secretsManager = new SecretsManager({ ...awsCreds })
  const getSecret = s => secretsManager.getSecretValue(s).then(get('SecretString'))

  serve({
    env,
    port: 4507,
    entrypoint: '/index.js',
    // entrypoint: `/${env}-${package.version}.js`
    bypassPublicCache: true,
  })
})
